Session:
  connection: 0
  tableName: session
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    session_key:
      type: string(100)
      notnull: true
    ip:
      type: string(15)
      notnull: true
    expiration:
      type: string(255)
    user_id:
      type: integer(4)
  relations:
    User:
      local: user_id
      foreign: id
User:
  connection: 0
  tableName: user
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    email:
      type: string(256)
      notnull: true
      email: true
    username:
      type: string(256)
      notnull: true
    password:
      type: string(256)
      notnull: true
    is_admin:
      type: integer(1)
      default: 0
      notnull: true
    is_deleted:
      type: integer(1)
      default: 0
      notnull: true
  relations:
