Basket:
  connection: 0
  tableName: basket
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    ip:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fk_user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fk_product_id:
      type: string(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    quantity:
      type: string(11)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    create_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mod_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Bus:
  connection: 0
  tableName: bus
  columns:
    bus_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    bus_name:
      type: string(50)
      name: bus_name as name
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    size:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '50'
      notnull: false
      autoincrement: false
    bus_chief_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fk_group_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Users:
      class: User
      local: bus_id
      foreign: fk_bus_id
      type: many
    Chief:
      class: User
      local: bus_chief_id
      foreign: id
      type: one
    Group:
      class: Group
      local: fk_group_id
      foreign: id
      type: one
Config:
  connection: 0
  tableName: config
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nb_places:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Couple:
  connection: 0
  tableName: couple
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    place_in_bus:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fk_paying_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    own_table:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    fk_friendship_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    Friendship:
      foreign: friendship_id
      local: fk_friendship_id
      type: one
    Users:
      class: User
      local: id
      foreign: fk_couple_id
      type: many
DebTmpKeys:
  connection: 0
  tableName: deb_tmp_keys
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    thekey:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ip:
      type: string(16)
      fixed: false
      unsigned: false
      primary: false
      default: 0.0.0.0
      notnull: true
      autoincrement: false
    expiration:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    type:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    uid:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Friendship:
  connection: 0
  tableName: friendship
  columns:
    friendship_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
  relations:
    Couples:
      class: Couple
      local: friendship_id
      foreign: fk_friendship_id
      type: many
Group:
  connection: 0
  tableName: groupe
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    group_name:
      type: string(50)
      name: group_name as name
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      notblank: true
    size:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '200'
      notnull: false
      autoincrement: false
    group_chief_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Users:
      class: User
      local: id
      foreign: fk_group_id
      type: many
    Chief:
      class: User
      local: group_chief_id
      foreign: id
      type: one
    Buses:
      class: Bus
      local: id
      foreign: fk_group_id
      type: many
MailQueue:
  connection: 0
  tableName: mail_queue
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    sender_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    dest_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    subject:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    body:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sent:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Notes:
  connection: 0
  tableName: notes
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    type:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    content:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    author:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    created:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Orders:
  connection: 0
  tableName: orders
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fk_user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    items:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    quantity:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    total_price:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    confirmed:
      type: enum(3)
      fixed: false
      unsigned: false
      values:
        - yes
        - no
      primary: false
      default: no
      notnull: true
      autoincrement: false
    order_date:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Pages:
  connection: 0
  tableName: pages
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    last_save:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ip:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    lang:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Prefs:
  connection: 0
  tableName: prefs
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    last_save:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ip:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    lang:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    search_opt:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    showcount:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      default: ''
      notnull: true
      autoincrement: false
    referer:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fk_country:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Products:
  connection: 0
  tableName: products
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    name:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    name_en:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    description_en:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    price:
      type: float()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    taxes:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image_path:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RegistrationPayement:
  connection: 0
  tableName: registration_payement
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    fk_user_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nb_tables:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    paypal_id:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    is_cancelled:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    is_renbursed:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    created_at:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
User:
  connection: 0
  tableName: user
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    invite_key:
      type: string(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    inviter:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    recommended_by:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    previous_deb:
      type: enum(1)
      fixed: false
      unsigned: false
      values:
        - y
        - n
      primary: false
      notnull: false
      autoincrement: false
    invite_quotas:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    invite_email:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      email: true
    invite_status:
      type: integer(3)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    sex:
      type: enum(1)
      fixed: false
      unsigned: false
      values:
        - m
        - f
      primary: false
      notnull: true
      autoincrement: false
    name:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      notblank: true
    address:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tel1:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tel2:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type:
      type: string(1)
      fixed: true
      unsigned: false
      primary: false
      default: S
      notnull: true
      autoincrement: false
    login_email:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      email: true
    password:
      type: string(256)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_admin:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    is_vip:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    is_blacklisted:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
    fk_couple_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fk_paypal:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fk_group_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fk_bus_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  indexes:
    login_email:
      fields:
        login_email:
          sorting: ASC
          length: 10
      type: unique
  relations:
    Group:
      local: fk_group_id
      foreign: id
      type: one
    GroupChiefOf:
      class: Group
      local: id
      foreign: group_chief_id
      type: one
    Bus:
      local: fk_bus_id
      foreign: bus_id
      type: one
    BusChiefOf:
      class: Bus
      local: id
      foreign: bus_chief_id
      type: one
    Couple:
      local: fk_couple_id
      foreign: id
      type: one
