<?php

/**
 * Bus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Bus extends BaseBus
{
    static function all()
    {
        $q = Doctrine_Query::create()
                ->from('Bus b');
        return $q->execute();

    }
    
    static function fetch($id)
    {
        $q = Doctrine_Query::create()
                ->from('Bus b')
                ->leftJoin('b.Users u')
                ->leftJoin('b.Chief c')
                ->leftJoin('b.Groupe g')
                ->leftJoin('g.Chief cg')
                ->where('b.id = ?', $id);

        return $q->fetchOne();

    }
    
    static function oneInCollection($id)
    {
        $q = Doctrine_Query::create()
                ->from('Bus b')
                ->where('b.id = ?', $id);
        return $q->execute();
    }

    static function summary($id = null)
    {
        $q = Doctrine_Query::create()
            ->select('
                COUNT(DISTINCT b.id) as nb_buses,
                COUNT(DISTINCT u.id) as nb_users')
                ->from('Bus b')
                ->leftJoin('b.Users u');
        if($id){
                $q = $q->where('b.Groupe.id = ?', $id);
        }

        $summary = $q->fetchOne()->toArray();

        $summary['sum_size'] = $summary['nb_buses']*50;
        return $summary;
    }

    static function getBuses()
    {
        $q = Doctrine_Query::create()
            ->select('b.*, c.*,
                COUNT(DISTINCT u.id) as nb_users')
            ->from('Bus b')
            ->leftJoin('b.Chief c')
            ->leftJoin('b.Users u')
            ->orderBy('b.fk_group_id, b.id')
            ->groupBy('b.id');

        return $q->execute();
    }

    static function getBusesOfGroupe($id)
    {
        $q = Doctrine_Query::create()
            ->select('b.*, c.*,
                COUNT(DISTINCT u.id) as nb_users')
            ->from('Bus b')
            ->leftJoin('b.Chief c')
            ->leftJoin('b.Users u')
            ->where('b.Groupe.id = ?', $id)
            ->groupBy('b.id');

        return $q->execute();
    }

    static function update_from_post($bus)
    {
        $bus->name = $_POST['bus_name'];
        //$bus->location = $_POST['bus_location'];
        //$bus->googlemaps_url = $_POST['bus_googlemaps_url'];
        if(isset($_POST['bus_size'])){
            $bus->size = $_POST['bus_size'];
        }
        return $bus;
    }

    static function create_from_post()
    {
        $bus = new Bus();
        return Bus::update_from_post($bus);
    }

    public function busICanSee($user)
    {
        if($user->isAdmin())
            return Bus::all();
        if($user->GroupeChiefOf)
            return $user->GroupeChiefOf->Buses;
        return Bus::oneInCollection($user->fk_bus_id);
    }
}
