<?php

/**
 * Config
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Config extends BaseConfig
{
    static function get_config()
    {
        $q = Doctrine_Query::create()
                ->from('Config u');
        return $q->fetchOne()->toArray();
    }
    static function get_nb_a_envoyer()
    {
        $q = Doctrine_Query::create()
            ->select('SUM(u.invite_quotas) as sum')
            ->from('User u')
            ->where('u.type != "A"');
        return $q->fetchOne()->toArray();
    }
    static function get_nb_confirmes()
    {
        $q = Doctrine_Query::create()
            ->select('COUNT(u.id) as cnt')
            ->from('User u')
            ->where('u.invite_status > 3');
        return $q->fetchOne()->toArray();

    }

}
