<?php

/**
 * Couple
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Couple extends BaseCouple
{
    static function getBusMembers($id)
    {
        $q = Doctrine_Query::create()
                //->select('c.*, u.*')
                ->from('User u')
                //->leftJoin('u.Couple c')
                ->where('u.Bus.id = ?', $id);
        return $q->execute();
    }

}
