<?php

/**
 * Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Faq extends BaseFaq
{
    static function fetch($slug)
    {
        $q = Doctrine_Query::create()
                ->from('Faq p')
                ->where('p.id = ?', $slug);
        return $q->fetchOne();
    }



}
