<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * models/Faq.php
 *
 * php version 5
 *
 * @category   Model
 * @package    CMS_Model
 * @subpackage CMS_FAQ
 * @author     julien jouvent-halle <julienhalle@heptacube.com>
 * @license    http://www.opensource.org/licenses/mit-license.php mit license
 * @link       http://github.com/jouvent/genitura
 * @since      0.0.2
 */

/**
 * Faq
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @category   Model
 * @package    CMS_Model
 * @subpackage CMS_FAQ
 * @author     julien jouvent-halle <julienhalle@heptacube.com>
 * @license    http://www.opensource.org/licenses/mit-license.php mit license
 * @link       http://github.com/jouvent/genitura
 * @since      0.0.2
 */
class Faq extends BaseFaq
{
    /**
     * fetch 
     * 
     * @param string $slug a unique string for the Faq
     *
     * @static
     * @access public
     * @return Faq
     */
    static function fetch($slug)
    {
        $q = Doctrine_Query::create()
                ->from('Faq p')
                ->where('p.id = ?', $slug);
        return $q->fetchOne();
    }



}
