<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */

/**
 * models/Page.php
 *
 * php version 5
 *
 * @category   Model
 * @package    CMS_Model
 * @subpackage CMS_Page
 * @author     julien jouvent-halle <julienhalle@heptacube.com>
 * @license    http://www.opensource.org/licenses/mit-license.php mit license
 * @link       http://github.com/jouvent/genitura
 * @since      0.0.2
 */

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @category   Model
 * @package    CMS_Model
 * @subpackage CMS_Page
 * @author     julien jouvent-halle <julienhalle@heptacube.com>
 * @license    http://www.opensource.org/licenses/mit-license.php mit license
 * @link       http://github.com/jouvent/genitura
 * @since      0.0.2
 */
class Pages extends BasePages
{

}
