<?php

/**
 * Pages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Pages extends BasePages
{
    static function fetchBySlug($slug)
    {
        $q = Doctrine_Query::create()
                ->from('Pages p')
                ->where('p.slug = ?', $slug);
        return $q->fetchOne();
    }



}
